name: Fx.CSS3

current: 1.0.2

web: "[github.com/mcfedr/mootools-fx-css3](http://github.com/mcfedr/mootools-fx-css3)"

description: "Native CSS3 transition for Fx (if available)"

authors: "[Fred Cox](http://fedr.co), [André Fiedler](http://visualdrugs.net)"

license: "MIT License"

copyright: "Copyright (c) 2011 Fred Cox mcfedr@gmail.com"
copyright: "Copyright (c) 2010, Dipl.-Ing. (FH) André Fiedler <kontakt at visualdrugs dot net>, based on code by eskimoblood (mootools users group)"

sources:
  - "Source/Fx.CSS3.js"
  - "Source/Fx.CSS3.Replacement.js"
  
# Values for MooTools forge
  
author: mcfedr

demo: http://jsfiddle.net/mcfedr/6tX7A/

category: Effects

tags: [Effects, CSS3, transition, animation, element, behavioral]
