name: Fx.Tween.CSS3

current: 1.0.1

web: "[github.com/SunboX/mootools-fx-tween-css3](http://github.com/SunboX/mootools-fx-tween-css3)"

description: "Native CSS3 transition for Fx.Tween (if available)"

authors: "[André Fiedler](http://visualdrugs.net)"

license: "MIT License"

copyright: "Copyright (c) 2010, Dipl.-Ing. (FH) André Fiedler <kontakt at visualdrugs dot net>, based on code by eskimoblood (mootools users group)"

sources:
  - "Source/Fx.Tween.CSS3.js"
  - "Source/Fx.Tween.CSS3.Replacement.js"
  
# Values for MooTools forge
  
author: SunboX

demo: http://jsfiddle.net/SunboX/qTnfb/

category: Effects

tags: [Effects, CSS3, transition, animation, element, behavioral]
